# UR3 - Cranfield University:

Configurations:

  - ID: "ur3_1"
    Name: "UR3 Robot alone on Cranfield University (IA Lab) Stand."
    urdf: "---.urdf.xacro"
    rob: ""
    ee: ""

  - ID: "ur3_2"
    Name: "UR3 Robot + Robotiq HandE Gripper on Cranfield University (IA Lab) Stand."
    urdf: "---.urdf.xacro"
    rob: ""
    ee: ""

  - ID: "ur3_3"
    Name: "UR3 Robot + Robotiq HandE Gripper on Cranfield University (IA Lab) Stand: Cube Pose Estimation use-case."
    urdf: "ur3_rosconuk25_3.urdf.xacro"
    rob: "ur3"
    ee: "robotiq_hande"